# Laravel Cloud Platform Configuration
name: app
type: php:8.2

runtime:
    extensions:
        - pdo_pgsql
        - sodium
        - gd
        - zip

build:
    flavor: composer

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

disk: 2048

mounts:
    "storage":
        source: local
        source_path: "storage"
    "bootstrap/cache":
        source: local
        source_path: "cache"

hooks:
    build: |
        set -e
        composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
    deploy: |
        set -e
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan migrate --force
